### ISSUE TITLE
Compile for windows

### ISSUE THREAD

**Issue by jeremyoha450** [Micronarrativ/mp3wrap#1]
Hi there

how would i compile this for windows? as i would like to make a change to the code.

regards

**Comment by Micronarrativ** [comment]
Hei,

I assume you're using it in Linux environment within your Windows-machine. Have a look at the file [INSTALL](./INSTALL) in the root directory of the repo. That should give you some hints on how to create the required files.
Other than that you'll require the usual tools: Make, gcc IIRC

Hope this helps.

**Comment by Spreadcat** [comment]
Closing due to no answer.
